### ISSUE TITLE
'Cannot find module' errors

### ISSUE THREAD

**Issue by chevalric** [nikku/karma-browserify#114]
We’ve recently started using karma-browserify, which you maintain, and we had the problem that on some machines the tests would fail (with `Cannot find module` errors) because the Browserify bundling would reset before it completed the first time. Increasing the bundleDelay option to 1500 solved this issue.

We have a big app (about 3.5Mb, bundled), so maybe it just needs more time than it got at first? Can you shed some light on why we need to increase bundleDelay?

**Comment by nikku** [comment]
Probably because you are using Mac OS X. It seems to have issues with propagating file system change events in a timely manner. This is not an issue on Windows and Linux (I am personally working with (app + test) bundles bigger than 10 mega bytes on Linux with no problems.

If you experience these issues on platforms other than Mac, it may be worth investigating. Else, you may checkout #113, #49, #67 to learn what others went through.

What the `bundleDelay` does: karma-browserify needs to wait for all files to be loaded by karma before it can actually start bundling. The `bundleDelay` is the timeout we accept until we assume karma handed over all files to us. If you have a slow disk (that needs more than the default delay to serve subsequent files the plug-in starts bundling without some files (the ones it later prints `Cannot find module` for).

**Comment by chevalric** [comment]
I am using Mac OSX, so no need to reopen then. Thanks for the quick reply.
