### ISSUE TITLE
Automatically increase bundleDelay on Mac OS X

### ISSUE THREAD

**Issue by nikku** [nikku/karma-browserify#116]
This ensures Mac OS users do not run into the usual bundling twice errors.

@bendrucker Is this a good idea?

**Comment by bendrucker** [comment]
I'm pretty torn on what to do about this. At some point you get into a situation where people are upset about poor perf for smaller projects. It's hard to say which outcome is worse: some people who observe a bug, or some people with general frustration. Both cases are fixed by docs, but it's not a smooth experience.

As costly as managing file lookups outside of Karma will be, I think that's the path to go down. Would make the code base a lot more readable as well since the average user isn't thinking about the insanity of needing to debounce updates with a delay.

**Comment by nikku** [comment]
Yes, with all the bug reports we are seeing I feel like it should better (usability wise) to have a slight automatically applied bundling penalty rather than endless re-bundling.

The issue with manual configuration is: You are penalizing other platforms too that would work fine without any adjustments. I see this as a huge issue in mixed platform development teams (which are common, especially in OSS).

Any idea what a good `bundleDelay` on Mac OSX is?

**Comment by nikku** [comment]
I just updated the version of watchify to the latest version. It updates some of file watching utilities, too and allows the customization of watchify`s very own `bundleDelay`.

Let's see if this already fixes some of the issues.

**Comment by bendrucker** [comment]
Will update keep my eye out for double bundling. The problem with assigning any particular delay is that it seems to be affected by a lot of factors, including disk speed. I'm guessing that I see it less often since I'm exclusively on SSDs.
