### ISSUE TITLE
Cannot get this package to work with a modular architecture

### ISSUE THREAD

**Issue by goodbomb** [nikku/karma-browserify#121]
I've built an angular-gulp-browserify start app and I've been having a very difficult time trying to get it to play nicely with Karma. It seems no matter what I do I can't get karma to find any of the app's modules.

https://github.com/goodbomb/angular-gulp-browserify-starter

That's the app. I'm trying to set it up so that a unit test file is included in each module directory as well as in each common resource / service / etc directory. The idea is that test files are included in each module folder alongside the files that are being tested.

Any help would be greatly appreciated.

**Comment by nikku** [comment]
Sounds good. 

One thing I currently see missing is the `browserify` framework in your [karma configuration](
https://github.com/goodbomb/angular-gulp-browserify-starter/blob/develop/karma.conf.js).

In order to get additional help, please tell us:
  
   * what did you try in order to get the integration to work
   * what where the issues

That helps us to give detailed feedback on issues that are related to _this package_.

**Comment by goodbomb** [comment]
Hi, thanks for the quick response last night. I hadn't updated my repo with the latest variations of my attempts yet when you responded, but I just did.

I have tried many different approaches to this problem, but every approach has only resulted in an error in some form or another.

One thing I noticed right away is that the only way a test file is recognized is if the file has "-test.js" at the end (which doesn't seem to be documented anywhere). If I try ".spec.js", I get an unhelpful ERROR message.

```PhantomJS 1.9.8 (Mac OS X): Executed 0 of 0 ERROR (0.002 secs / 0 secs)```

It would be nice if I could use my own test file naming convention, but regardless, if I change the name to use "-test.js" I still run into a module error when I'm using ```angular.mock.module('modules');```:

```
Error: [$injector:modulerr] Failed to instantiate module modules due to:
Error: [$injector:nomod] Module 'modules' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

If I try simply injecting the controller in a beforeEach hook like so: 
```
angular.mock.inject(function($rootScope, $controller) {
  scope = $rootScope.$new();
  ctrl = $controller('MainCtrl', {$scope: scope});
});
```

Then I still get the following error:

```
the object {
	  "line": 1587
	  "message": "[ng:areq] Argument 'MainCtrl' is not a function, got undefined
	http://errors.angularjs.org/1.3.15/ng/areq?p0=MainCtrl&p1=not%20a%20function%2C%20got%20undefined"
	  "name": "Error"
	  "sourceId": 128187232
	  "stack": "Error: [ng:areq] Argument 'MainCtrl' is not a function, got undefined
```

I've committed my most recent changes.

**Comment by nikku** [comment]
You are using incompatible karma-browserify + debowerify versions.

Use [karma-bro@v0.6.2](https://github.com/nikku/karma-browserify/releases/tag/v0.6.2) which uses browserify@4 under the hood and works well with your used debowerify transform version. Alternatively, upgrade to the latest browserify.

Your karma-browserify version + browserify (+transforms) version should always be on par with each other in terms of browserify compatibility. Otherwise these kinds of things can happen.

**Comment by goodbomb** [comment]
*Facepalm* yes of course. Updating my packages to their most recent versions would certainly have helped. I did just that and it works now. Thanks!

**Comment by nikku** [comment]
Glad it works!
