### ISSUE TITLE
karma-browserify with handlebars-runtime?

### ISSUE THREAD

**Issue by leiming** [nikku/karma-browserify#128]
My current problem is using https://github.com/epeli/node-hbsfy and https://github.com/Nikku/karma-browserify always throw `bundle error`while require hbs. Here is my  karma.conf.js

## karma.conf.js
```js
'use strict';

module.exports = function (karma) {
  karma.set({

    frameworks: ['jasmine', 'browserify'],

    files: [
      'src/**/*.js',
      'test/**/*Spec.js'
    ],

    // possible values: 'dots', 'progress', 'junit', 'growl', 'coverage'
    reporters: ['progress'],

    preprocessors: {
      'src/**/*.js'     : ['browserify'],
      'test/**/*Spec.js': ['browserify']
    },

    browsers: ['Chrome'],

    logLevel: 'LOG_DEBUG',

    //singleRun: true,
    autoWatch: true,

    // browserify configuration
    browserify: {
      debug     : true,
      transform : ['brfs', 'browserify-shim', ['hbsfy', {"extensions": "hbs"}]]
    }
  });
};
```

## index.js
```js
var handlebars = require('handlebars')

// maybe it is!
var template = require("./test.hbs")
var context = {title: "My New Post", body: "This is my first post!"};
template(context)
```

It seems that using preprocessor of https://github.com/petrbela/karma-handlebars-preprocessor may solve `hbs` to `js` in karma, but I have not succeed so far.

My question is: Could karma-browserify support handlebars? if it could, please give me some tips, thank you very much!

**Comment by bendrucker** [comment]
You don't need a preprocessor. Using browserify means you don't want to use any of those features of karma. Browserify does the important stuff via transforms.

Your browserify config is invalid. You must run hbsify first so all your files (including handlebars files you `require`) are valid js when they hit brfs and b-shim. Transforms that act on select extensions and transform them to valid JS should always come first, then stuff that does any code parsing.

**Comment by leiming** [comment]
Thank you so much for the speedy reply. @bendrucker 

I am trying to understanding the word `run` in ` You must run hbsify first so all your files  ... ` as not using command `browserify -t hbsfy main.js > bundle.js` in the usage of [hbsfy](https://github.com/epeli/node-hbsfy) but using hbsfy transforms.

So, I modify `karma.conf.js` as follow:

```

//...

    preprocessors: {
      'test/**/*Spec.js': ['browserify']
    },

//...

    browserify: {
      debug    : true,
      extensions: ["js", "hbs"], // Is it necessary?
      transform: [['hbsfy', {"extensions": "hbs"}], 'brfs', 'browserify-shim']
    }

```

Then, a spec.js require templates:

```
var template = require('./test.hbs')
```

When I start karma, the program always throw error:

> ERROR [framework.browserify]: bundle error
> ERROR [framework.browserify]: SyntaxError: Unexpected token (1:0) while parsing file: /**/test/test.hbs

This error is same as https://github.com/nikku/karma-browserify/issues/128#issue-79119347

Could you tell me the method of requiring `hbs` in `js` file?  or I have to run `browserify -t hbsfy` manually and using bundle.js?

**Comment by bendrucker** [comment]
Your transforms are called in sequence. Order matters. Browserify will call them in the defined order and so you need to make sure your files can run through the whole pipeline. 

A tool like browserify-shim is expecting JavaScript as an input. It needs to run your code through an AST parser in order to replace the `require` statements with shims. 

Something like hbsify is instead going to compile your Handlebars in Node and then write the output back to the file prefixed by `module.exports =`. 

So when I say hbs has to run first, that means it needs to be first in the transform array. That way when it gets to browserify-shim it's valid JS and not the original handlebars template.

It wasn't clear from your initial post that this was working on the CLI but not via karma-browserify. If that's the case then it would be a huge help if you could pull this into a repo I can run.

**Comment by leiming** [comment]
I create a repo to test [karma-browserify-handlebars](https://github.com/leiming/karma-browserify-handlebars),  and I'm so glad that both hbsfy CLI and karma-browserify are work.

 Thank you again for your patient answers. I am closing this issue for now.
