### ISSUE TITLE
Using karma-browserify and browserify-istanbul to generate test coverage report for a multimodule JS application

### ISSUE THREAD

**Issue by szgabsz91** [nikku/karma-browserify#129]
I try to generate test coverage report for my multimodule JS application. I uploaded a simplified example that demonstrates the problem: https://github.com/szgabsz91/browserify-karma-coverage

The submodule (`moduleA`) is an npm dependency of the `app` and I created a gulp task in the `app` package that executes the tests in both packages and generates a test coverage report. However, only the `app`'s files are included in this report, `moduleA` is ignored.

First I thought maybe the symlink causes this (I use `npm link` for testing), but replacing the link with a real folder works the same way.

I don't know how to fix my configuration, could you please help me? I guess at some point the `node_modules` folder is ignored, but I don't know where. Is it `karma`? Or `karma-browserify`? Or simply my configuration is wrong? But it's interesting that the tests are executed, only the coverage is problematic.

Thanks in advance, any help is appreciated.

**Comment by bendrucker** [comment]
Transforms don't run on code in `node_modules`. Your options are:

1. Run tests, coverage, etc. for `moduleA` independently. This is the right way to go because it's a separate package.
2. Add `{global: true}` to the transform options for the transform covering your code. This will now cover everything, including all deps. So you'd have to get super creative with globs for ignoring all but your code.
